### ISSUE TITLE
Transition between tabs

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#54]
When changing from one tab to other the animation on the fields below the tabs is too distracting, I don't think we need it.
Would it be possible to remove it?
![tabs-effect](https://user-images.githubusercontent.com/11855774/43228387-c2dce83e-9037-11e8-9dcf-c3365b2504df.gif)

Thank you.

**Comment by jfoclpf** [comment]
what would be better in your opinion?
 
- hide and show the elements immediately, or  
- smoothly fadeIn/fadeOut (no animation)

**Comment by mcristaldo** [comment]
I would go with "a", hide/show the elements immediately, no animation at all in any of the tabs through the form. 
As simple as this one: https://codepen.io/oknoblich/pen/tfjFl

What do you think?

**Comment by jfoclpf** [comment]
I find it ok with solution "a". I will do it right now

**Comment by jfoclpf** [comment]
solved with 004b219e97e85c1cb7e38a0b4cf320fa55954fe7

It's already online @mcristaldo 
What do you think?

**Comment by mcristaldo** [comment]
Hi Joao, there are some tabs with animation still. Like this one:
![tabs-animation](https://user-images.githubusercontent.com/11855774/43605599-3a819c58-966f-11e8-90f5-77b580a94db1.gif)

**Comment by jfoclpf** [comment]
solved with 46025650b135768ac04a37dc3cdb8a0899ddb0f9
Can you test now?

**Comment by mcristaldo** [comment]
The one you fixed is perfect, but these guys still have the animation:
![tabs-effect-2](https://user-images.githubusercontent.com/11855774/43608928-ee275776-9678-11e8-8638-e56aa876a492.gif)
![tabs-effect-3](https://user-images.githubusercontent.com/11855774/43608929-ee4d3676-9678-11e8-984c-0596ceaa0241.gif)

Thanks.

**Comment by jfoclpf** [comment]
well catched. I will solve now

**Comment by jfoclpf** [comment]
Solved, I think, with 3b44f0f60178c5f7ace0c33c4f09e5f8787a456e
can you test now?

**Comment by mcristaldo** [comment]
Great, solved
